<div class="cadTitle">
	<strong>Relatórios</strong><span> Produtores</span>
	<form id="formCadastro" method="post" class="bulletForm" action="/index/actincluir">
		
		<div class="bulletFormEndereco">
	        <input style="width: 15px; text-align: center;" name="uf" type="text" id="uf" placeholder="UF" title="Coloque a sigla de seu estado">
	        <input style="width: 205px;" type="text" name="cidade" placeholder="CIDADE" id="cidade" title="Preencha com sua cidade">
	    </div>
		
		<div class="checks">
	        <input type="checkbox" name="master" value="1" id="produtor_master"/>
	        <label for="produtor_master"><span></span>PRODUTOR MASTER</label>
	        <div class="infoVal2">
	        <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_diario" type="text" placeholder="Mínimo diário" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_diario" type="text" placeholder="Máximo diário" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_mensal" type="text" placeholder="Mínimo mensal" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_mensal" type="text" placeholder="Máximo mensal" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        </div>
	    </div>
	
	    <div class="checks">
	        <input type="checkbox" name="executivo" value="1" id="produtor_executivo"/>
	        <label for="produtor_executivo"><span></span>PRODUTOR EXECUTIVO</label>
	        <div class="infoVal2">
	         <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_diario" type="text" placeholder="Mínimo diário" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_diario" type="text" placeholder="Máximo diário" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_mensal" type="text" placeholder="Mínimo mensal" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_mensal" type="text" placeholder="Máximo mensal" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        </div>
	    </div>
	
	    <div class="checks">
	        <input type="checkbox" name="assistente" value="1" id="assistente"/>
	        <label for="assistente"><span></span>ASSISTENTE</label>
	        <div class="infoVal2">
	         <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_diario" type="text" placeholder="Mínimo diário" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_diario" type="text" placeholder="Máximo diário" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_mensal" type="text" placeholder="Mínimo mensal" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_mensal" type="text" placeholder="Máximo mensal" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        </div>
	    </div>
	
	    <div class="checks">
	        <input type="checkbox" name="produtor" value="1" id="produtor_ab"/>
	        <label for="produtor_ab"><span></span>PRODUTOR DE A&B</label>
	        <div class="infoVal2">
	         <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_diario" type="text" placeholder="Mínimo diário" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_diario" type="text" placeholder="Máximo diário" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_mensal" type="text" placeholder="Mínimo mensal" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_mensal" type="text" placeholder="Máximo mensal" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        </div>
	    </div>
	
	    <div class="checks">
	        <input type="checkbox" name="servicos" value="1" id="produtor_servicos"/>
	        <label for="produtor_servicos"><span></span>PRODUTOR DE SERVIÇOS</label>
	        <div class="infoVal2">
	         <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_diario" type="text" placeholder="Mínimo diário" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_diario" type="text" placeholder="Máximo diário" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_mensal" type="text" placeholder="Mínimo mensal" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_mensal" type="text" placeholder="Máximo mensal" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        </div>
	    </div>
	
	    <div class="checks">
	        <input type="checkbox" name="financeiro" value="1" id="produtor_financeiro"/>
	        <label for="produtor_financeiro"><span></span>PRODUTOR FINANCEIRO</label>
	        <div class="infoVal2">
	         <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_diario" type="text" placeholder="Mínimo diário" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_diario" type="text" placeholder="Máximo diário" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_mensal" type="text" placeholder="Mínimo mensal" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_mensal" type="text" placeholder="Máximo mensal" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        </div>
	    </div>
	
	     <div class="checks">
	        <input type="checkbox" value="1" name="logistico" id="produtor_logistico"/>
	        <label for="produtor_logistico"><span></span>PRODUTOR LOGÍSTICO</label>
	        <div class="infoVal2">
	         <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_diario" type="text" placeholder="Mínimo diário" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_diario" type="text" placeholder="Máximo diário" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_mensal" type="text" placeholder="Mínimo mensal" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_mensal" type="text" placeholder="Máximo mensal" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        </div>
	    </div>
	
	     <div class="checks">
	        <input type="checkbox" name="apoio" value="1" id="apoio"/>
	        <label for="apoio"><span></span>APOIO</label>
	        <div class="infoVal2">
	         <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_diario" type="text" placeholder="Mínimo diário" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_diario" type="text" placeholder="Máximo diário" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        <div class="infoVal">
	            de <input class="input-xxlarge valor" name="master_min_mensal" type="text" placeholder="Mínimo mensal" title="Informe o valor mínimo de seu cachê diário">
	           	até
	            <input class="input-xxlarge valor" name="master_max_mensal" type="text" placeholder="Máximo mensal" title="Informe o valor mínimo de seu cachê mensal">
	        </div>
	        </div>
	    </div>
	    <div align="center">
		    <button type="submit">BUSCAR</button>	
	    </div>
	    
	</form>
</div>
<a href="/index/logout" style="margin-left: -100px;">Sair</a>

<script>
	$(document).ready(function(){
		$(".infoVal2").css("display","none");
		$(".valor").width("80px");
		$("input[type='checkbox']").click(function(){
			if($(this).is(":checked"))
			{
				$(this).next().next().slideDown();
				
			}	
			else{
				$(this).next().next().slideUp();
			}
				
			
		});
	});
</script>