<!DOCTYPE HTML>
<html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
        <title>Bullet Eventos - Formulário de cadastro de produtores</title>

        <!-- FAVICON -->
        <link rel="shortcut icon" href="http://www.bulleteventos.com.br/wp-content/themes/bullet_eventos/favicon.ico" >
 
        <!-- JQUERY -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/js/jquery-1.7.1.min.js"><\/script>')</script>

        <!--[if IE]>
        <link href="/css/bulleteventosIE.css" rel="stylesheet" type="text/css" />
        <![endif]-->
 
        <!-- TWITTER BOOTSTRAP CSS -->
        <link href="/css/bootstrap.css" rel="stylesheet" type="text/css" />

        <!-- BULLET EVENTOS CSS -->
        <link href="/css/bulleteventos.css" rel="stylesheet" type="text/css" />
 
        <!-- TWITTER BOOTSTRAP JS -->
        <script src="/js/bootstrap.min.js"></script>

        <!-- MASK JS -->
        <script src="/js/jquery.maskedinput-1.3.min.js"></script>

        <!-- PLACEHOLDER PARA IE -->
        <script src="/js/jquery.placeholder.js"></script>
        
        <script src="/js/jquery.form.js"></script>
        
        <script src="/js/jquery.validate.js"></script>
 
    </head>
    <body>
        <!-- HEADER -->
        <header class="container-fluid">
            <div class="row-fluid">
                <address>
                    CONTATO · Geral: 11 3089-7133 · Juliana Queiroz (Diretora de Atendimento): 11 3089-7138 · <a href=" mailto:juliana@bullet.com.br">juliana@bullet.com.br</a>  
                </address>
                
            </div>
        </header>
        <!-- / HEADER -->
 
        <!-- CLASSE QUE DEFINE O CONTAINER COMO FLUIDO (100%) -->
        <div class="container-fluid">
            <!-- CLASSE PARA DEFINIR UMA LINHA -->
            <div class="row-fluid">
                <!-- COLUNA OCUPANDO 03 ESPAÇOS NO GRID -->
                <div class="span3 sideBar">
                    <img src="/img/header_bullet_eventos_logo.gif" alt="Bullet Eventos" width="226" height="217" />
                    <div class="talkability">
                        <a href="http://www.talkability.com.br/4720/o-que-e-talkability/" target="_blank">
                            <img src="/img/img_trans.gif" alt="Talkability" width="1" height="1" />
                        </a>
                    </div>
                </div>
                <!-- COLUNA OCUPANDO 05 ESPAÇOS NO GRID -->
                
                <!-- CONTEÚDO -->
                <div class="span5">
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
    </body>
</html>
 <script type="text/javascript">
            $('input, textarea').placeholder();
        </script>

        <script type="text/javascript">
            $("#myform :input").tooltip({
            position: "center right",
            offset: [-2, 10],
            effect: "fade",
            opacity: 0.7
            });
        </script>
        <script type="text/javascript">
        $(function($){
           $("#telefone").mask("(99) 9999-9999");
           $("#celular").mask("(99) 99999-9999");
           $("#cep").mask("99999-999");
           $("#rg").mask("99.999.999");
           $("#cpf").mask("999.999.999-99")
        });
        </script>
        